import h5py
import os
import numpy as np
import matplotlib.pyplot as plt

# =============================================================================
# Legacy helper functions (kept for backward compatibility)
# =============================================================================

def get_h5_output(filepath, outcome):
    """
    Retrieves data or a list of group/dataset names from an HDF5 file.
    
    WARNING: This function opens and closes the file each time it's called.
    For better performance, use the optimized methods in JamAnalysis class.

    Args:
        filepath (str): Path to the HDF5 file.
        outcome (str): The path to the dataset or group within the HDF5 file.

    Returns:
        list or numpy.ndarray: If `outcome` points to a group, returns a list of
            names of items within that group. If `outcome` points to a dataset,
            returns the data as a NumPy array (or list if not directly convertible).
    """
    with h5py.File(filepath, "r") as f:
        data = list(f[outcome])   
    return data

def get_h5_type(filepath, outcome):
    """
    Determines if a given path in an HDF5 file points to a Group or a Dataset.
    
    WARNING: This function opens and closes the file each time it's called.
    For better performance, use the optimized methods in JamAnalysis class.

    Args:
        filepath (str): Path to the HDF5 file.
        outcome (str): The path to the item within the HDF5 file.

    Returns:
        str: "Group" if the item is an h5py.Group, "Dataset" if it is an
             h5py.Dataset, or None if it's neither (or an error occurs).
    """
    with h5py.File(filepath, "r") as f:
        if isinstance(f[outcome], h5py.Dataset):
            return "Dataset"
        elif isinstance(f[outcome], h5py.Group):
            return "Group"

def get_h5_groups_datasets(filepath, path, outcomes):
    """
    Separates a list of HDF5 item names into groups and datasets.
    
    WARNING: This function opens and closes the file multiple times.
    For better performance, use the optimized methods in JamAnalysis class.

    Args:
        filepath (str): Path to the HDF5 file.
        path (str): The base path within the HDF5 file where the items in `outcomes` are located.
        outcomes (list of str): A list of item names (groups or datasets) to categorize.

    Returns:
        tuple: A tuple containing two lists:
            - groups (list of str): Names of items that are HDF5 groups.
            - datasets (list of str): Names of items that are HDF5 datasets.
    """
    groups = []
    datasets = []
    for outcome in outcomes:
        if get_h5_type(filepath, path + outcome) == 'Group':
            groups.append(outcome)
        elif get_h5_type(filepath, path + outcome) == 'Dataset':
            datasets.append(outcome)
    return groups, datasets


class JamAnalysis:
    """
    A class for performing Joint and Articular Mechanics (JAM) analysis from HDF5 files
    generated by tools like OpenSim's JointMechanicsTool.

    This class reads data related to forces (ForceSet, including specific contact forces),
    coordinates (CoordinateSet), frame transforms, and COMAK-specific outputs from one
    or more HDF5 files. It organizes this data into dictionaries for easier access and
    provides methods for processing and plotting.
    
    OPTIMIZED: This class now opens each H5 file only once, dramatically improving
    performance (from ~17 seconds to ~0.3 seconds per file on NAS storage).

    Attributes:
        h5_file_list (list): List of HDF5 file paths to analyze.
        num_files (int): Number of HDF5 files.
        base_name (str): Base key in HDF5, usually 'model'.
        names (list): Names or identifiers for each file/trial.
        forceset (dict): Stores ForceSet data.
        coordinateset (dict): Stores CoordinateSet data.
        frametransformsset (dict): Stores FrameTransformsSet data.
        comak (dict): Stores COMAK-specific data if present.
        time (numpy.ndarray): Time vector from the HDF5 files.
        num_time_steps (int): Number of time steps.
    """
    def __init__(
        self,
    ):
        """
        Initializes the JamAnalysis class with default empty attributes.
        """
        self.h5_file_list = []
        self.num_files = 0
        self.base_name = 'model'
        self.names = []
        self.num_missing_files = 0
        self.missing_files = []

        self.forceset_name = 'forceset'
        self.coordset_name = 'coordinateset'
        self.frametransformsset_name = 'frametransformsset'

        self.SmithArticularContactName = 'Smith2018ArticularContactForce'

        self.forceset = {}
        self.coordinateset = {}
        self.frametransformsset = {}
        self.comak = {}
    
    # =========================================================================
    # OPTIMIZED processing methods - work with open file handle
    # =========================================================================
    
    def _process_forceset_fast(self, f, h5_file_idx):
        """
        Process forceset data with an already-open file handle.
        
        Args:
            f: Open h5py.File handle
            h5_file_idx: Index of current file being processed
        """
        base_path = f'/{self.base_name}/{self.forceset_name}'
        
        if base_path not in f:
            return
        
        forceset_group = f[base_path]
        
        for component in forceset_group.keys():
            if component not in self.forceset:
                self.forceset[component] = {}
            
            component_group = forceset_group[component]
            
            for forceset_name in component_group.keys():
                if forceset_name not in self.forceset[component]:
                    self.forceset[component][forceset_name] = {}
                
                forceset_grp = component_group[forceset_name]
                
                if component == self.SmithArticularContactName:
                    self._process_contact_fast(f, forceset_grp, component, forceset_name, h5_file_idx)
                else:
                    self._process_generic_forceset_fast(forceset_grp, component, forceset_name, h5_file_idx)
    
    def _process_contact_fast(self, f, forceset_grp, component, forceset_name, h5_file_idx):
        """
        Process Smith2018ArticularContactForce data with open file handle.
        
        Args:
            f: Open h5py.File handle
            forceset_grp: The forceset group (e.g., tf_contact)
            component: Component name (Smith2018ArticularContactForce)
            forceset_name: Name of the forceset (e.g., tf_contact)
            h5_file_idx: Index of current file
        """
        for mesh_name in forceset_grp.keys():
            if mesh_name not in self.forceset[component][forceset_name]:
                self.forceset[component][forceset_name][mesh_name] = {x: {} for x in range(6)}
            
            mesh_group = forceset_grp[mesh_name]
            
            for item_name in mesh_group.keys():
                item = mesh_group[item_name]
                
                if isinstance(item, h5py.Group):
                    # It's a group containing regional data (like regional_contact_force with region subgroups)
                    for region_idx, region_name in enumerate(item.keys()):
                        data = np.array(item[region_name])
                        n_rows, n_cols = data.shape
                        
                        if region_idx not in self.forceset[component][forceset_name][mesh_name]:
                            self.forceset[component][forceset_name][mesh_name][region_idx] = {}
                        
                        if item_name not in self.forceset[component][forceset_name][mesh_name][region_idx]:
                            self.forceset[component][forceset_name][mesh_name][region_idx][item_name] = \
                                np.zeros((n_rows, n_cols, self.num_files))
                        
                        self.forceset[component][forceset_name][mesh_name][region_idx][item_name][:, :, h5_file_idx] = data
                
                elif isinstance(item, h5py.Dataset):
                    # It's a dataset
                    data = np.array(item)
                    
                    if 'regional' in item_name:
                        # Regional scalar data (pressure, area) - has shape (n_timesteps, n_regions)
                        n_rows = data.shape[0]
                        n_regions = data.shape[1] if len(data.shape) > 1 else 1
                        
                        for region_idx in range(min(6, n_regions)):
                            if item_name not in self.forceset[component][forceset_name][mesh_name][region_idx]:
                                self.forceset[component][forceset_name][mesh_name][region_idx][item_name] = \
                                    np.zeros((n_rows, self.num_files))
                            
                            if len(data.shape) > 1:
                                self.forceset[component][forceset_name][mesh_name][region_idx][item_name][:, h5_file_idx] = \
                                    data[:, region_idx]
                            else:
                                self.forceset[component][forceset_name][mesh_name][region_idx][item_name][:, h5_file_idx] = data
                    else:
                        # Non-regional data (like total_contact_force)
                        if len(data.shape) == 1:
                            if item_name not in self.forceset[component][forceset_name][mesh_name]:
                                self.forceset[component][forceset_name][mesh_name][item_name] = \
                                    np.zeros((data.shape[0], self.num_files))
                            self.forceset[component][forceset_name][mesh_name][item_name][:, h5_file_idx] = data
                        else:
                            if item_name not in self.forceset[component][forceset_name][mesh_name]:
                                self.forceset[component][forceset_name][mesh_name][item_name] = \
                                    np.zeros((data.shape[0], data.shape[1], self.num_files))
                            self.forceset[component][forceset_name][mesh_name][item_name][:, :, h5_file_idx] = data
    
    def _process_generic_forceset_fast(self, forceset_grp, component, forceset_name, h5_file_idx):
        """
        Process Muscle/Ligament data with open file handle.
        
        Args:
            forceset_grp: The forceset group for this muscle/ligament
            component: Component type (e.g., 'Muscle', 'Blankevoort1991Ligament')
            forceset_name: Name of the muscle/ligament
            h5_file_idx: Index of current file
        """
        for item_name in forceset_grp.keys():
            item = forceset_grp[item_name]
            
            if isinstance(item, h5py.Dataset):
                data = np.array(item)
                
                if item_name not in self.forceset[component][forceset_name]:
                    self.forceset[component][forceset_name][item_name] = \
                        np.zeros((self.num_time_steps, self.num_files))
                
                self.forceset[component][forceset_name][item_name][:, h5_file_idx] = data
    
    def _process_coordinateset_fast(self, f, h5_file_idx):
        """
        Process coordinateset data with an already-open file handle.
        
        Args:
            f: Open h5py.File handle
            h5_file_idx: Index of current file being processed
        """
        base_path = f'/{self.base_name}/{self.coordset_name}'
        
        if base_path not in f:
            return
        
        coordset_group = f[base_path]
        
        for coord_name in coordset_group.keys():
            if coord_name not in self.coordinateset:
                self.coordinateset[coord_name] = {}
            
            coord_group = coordset_group[coord_name]
            
            for item_name in coord_group.keys():
                item = coord_group[item_name]
                
                if isinstance(item, h5py.Dataset):
                    data = np.array(item)
                    
                    if item_name not in self.coordinateset[coord_name]:
                        self.coordinateset[coord_name][item_name] = \
                            np.zeros((self.num_time_steps, self.num_files))
                    
                    self.coordinateset[coord_name][item_name][:, h5_file_idx] = data
    
    def _process_frametransformsset_fast(self, f, h5_file_idx):
        """
        Process frametransformsset data with an already-open file handle.
        
        Args:
            f: Open h5py.File handle
            h5_file_idx: Index of current file being processed
        """
        base_path = f'/{self.base_name}/{self.frametransformsset_name}'
        
        if base_path not in f:
            return
        
        print('PROCESSING FRAMETRANSFORMSET => THIS HAS NOT BEEN TESTED BEFORE, PLEASE VERIFY IF IT WORKS')
        
        frames_group = f[base_path]
        
        for frame_name in frames_group.keys():
            frame_group = frames_group[frame_name]
            
            for outcome_name in frame_group.keys():
                if 'coordinates' in outcome_name:
                    transform_type = 'coordinates'
                elif 'transformation_matrix' in outcome_name:
                    transform_type = 'transformation_matrix'
                else:
                    continue
                
                outcome_group = frame_group[outcome_name]
                
                for item_name in outcome_group.keys():
                    item = outcome_group[item_name]
                    
                    if isinstance(item, h5py.Dataset):
                        data = np.array(item)
                        
                        if transform_type not in self.frametransformsset:
                            self.frametransformsset[transform_type] = {}
                        
                        if item_name not in self.frametransformsset[transform_type]:
                            self.frametransformsset[transform_type][item_name] = \
                                np.zeros((self.num_time_steps, self.num_files))
                        
                        self.frametransformsset[transform_type][item_name][:, h5_file_idx] = data
    
    def _process_comak_fast(self, f, h5_file_idx):
        """
        Process COMAK data with an already-open file handle.
        
        Args:
            f: Open h5py.File handle
            h5_file_idx: Index of current file being processed
        """
        if '/comak' not in f:
            return
        
        comak_group = f['/comak']
        
        for item_name in comak_group.keys():
            item = comak_group[item_name]
            
            if isinstance(item, h5py.Dataset):
                data = np.array(item)
                
                if item_name not in self.comak:
                    self.comak[item_name] = np.zeros((data.shape[0], self.num_files))
                
                self.comak[item_name][:, h5_file_idx] = data
    
    # =========================================================================
    # Legacy processing methods (kept for backward compatibility)
    # These are slower but may be used by external code
    # =========================================================================
    
    def process_forceset(self, h5_filepath, h5_file_idx):
        """
        Processes the 'forceset' group from an HDF5 file.
        
        WARNING: This method opens the file multiple times and is slow.
        The jam_analysis() method now uses optimized internal methods instead.

        Reads data for various force components (e.g., Muscle, Blankevoort1991Ligament,
        Smith2018ArticularContactForce). For Smith2018ArticularContactForce, it handles
        nested structures including mesh names and regional data.
        Data is stored in the `self.forceset` dictionary, structured by component type,
        force element name, and then by specific parameters (or mesh/region for contacts).

        Args:
            h5_filepath (str): Path to the HDF5 file.
            h5_file_idx (int): Index of the current file being processed (used for organizing
                data when multiple files are loaded).
        """
        # Get the components & iterate over them 
        components = get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}')
        for component_idx, component in enumerate(components):
            if component not in self.forceset:
                self.forceset[component] = {}
            # Get the forcesets & iterate over them
            forcesets = get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}/{component}')
            for forceset_idx, forceset in enumerate(forcesets):
                if forceset not in self.forceset[component]:
                    self.forceset[component][forceset] = {} 
                if component == self.SmithArticularContactName:
                    # Get mesh names & iterate over them
                    mesh_names = get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}')
                    for mesh_idx, mesh_name in enumerate(mesh_names):
                        if mesh_name not in self.forceset[component][forceset]:
                            self.forceset[component][forceset][mesh_name] = {x:{} for x in range(6)}
                        # get params from mesh, break into "groups" and "datasets" & iterate over them as appropriate
                        params = get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}/{mesh_name}')
                        groups, datasets = get_h5_groups_datasets(
                            h5_filepath, 
                            f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}/{mesh_name}/',
                            params
                        )
                        
                        for group_idx, group in enumerate(groups):
                            # Iterate over "groups" & store results data in dict
                            regions = get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}/{mesh_name}/{group}')
                            for region_idx, region in enumerate(regions):
                                data = np.asarray(get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}/{mesh_name}/{group}/{region}'))
                                n_rows, n_cols = data.shape
                                if region_idx not in self.forceset[component][forceset][mesh_name]:
                                    self.forceset[component][forceset][mesh_name][region_idx] = {}
                                if group not in self.forceset[component][forceset][mesh_name][region_idx]:
                                    self.forceset[component][forceset][mesh_name][region_idx][group] = np.zeros((n_rows, n_cols, self.num_files))
                                self.forceset[component][forceset][mesh_name][region_idx][group][:, :, h5_file_idx] = data                                                                     
                        
                        for dataset_idx, dataset in enumerate(datasets):
                            data = np.asarray(get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}/{mesh_name}/{dataset}'))
                            if 'regional' in dataset:
                                for region_idx in range(6):
                                    if dataset not in self.forceset[component][forceset][mesh_name][region_idx]:
                                        n_rows = data.shape[0]
                                        self.forceset[component][forceset][mesh_name][region_idx][dataset] = np.zeros((n_rows, self.num_files))
                                    self.forceset[component][forceset][mesh_name][region_idx][dataset][:, h5_file_idx] = data[:, region_idx]
                            else:
                                if len(data.shape) == 1:
                                    if dataset not in self.forceset[component][forceset][mesh_name]:
                                        self.forceset[component][forceset][mesh_name][dataset] = np.zeros((data.shape[0], self.num_files))
                                    self.forceset[component][forceset][mesh_name][dataset][:, h5_file_idx] = data
                                else:
                                    if dataset not in self.forceset[component][forceset][mesh_name]:
                                        self.forceset[component][forceset][mesh_name][dataset] = np.zeros((data.shape[0], data.shape[1], self.num_files))
                                    self.forceset[component][forceset][mesh_name][dataset][:, :, h5_file_idx] = data
                
                else:
                    params = get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}')
                    groups, datasets = get_h5_groups_datasets(
                        h5_filepath, 
                        f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}/',
                        params
                    )

                    for dataset_idx, dataset in enumerate(datasets):
                        data = np.asarray(get_h5_output(h5_filepath, f'/{self.base_name}/{self.forceset_name}/{component}/{forceset}/{dataset}'))
                        if dataset not in self.forceset[component][forceset]:
                            self.forceset[component][forceset][dataset] = np.zeros((self.num_time_steps, self.num_files))
                        self.forceset[component][forceset][dataset][:, h5_file_idx] = data
    
    def process_coordinateset(self, h5_filepath, h5_file_idx):
        """
        Processes the 'coordinateset' group from an HDF5 file.
        
        WARNING: This method opens the file multiple times and is slow.
        The jam_analysis() method now uses optimized internal methods instead.

        Reads data for each coordinate (e.g., value, speed, acceleration) and stores it
        in the `self.coordinateset` dictionary, structured by coordinate name and then by parameter.

        Args:
            h5_filepath (str): Path to the HDF5 file.
            h5_file_idx (int): Index of the current file being processed.
        """
        coordinates = get_h5_output(h5_filepath, f'/{self.base_name}/{self.coordset_name}')
        for coord_idx, coord in enumerate(coordinates):
            if coord not in self.coordinateset:
                self.coordinateset[coord] = {}
            params = get_h5_output(h5_filepath, f'/{self.base_name}/{self.coordset_name}/{coord}')
            groups, datasets = get_h5_groups_datasets(
                h5_filepath, 
                f'/{self.base_name}/{self.coordset_name}/{coord}/',
                params
            )
            # Iteratve over the datasets
            for dataset_idx, dataset in enumerate(datasets):
                data = np.asarray(get_h5_output(h5_filepath, f'/{self.base_name}/{self.coordset_name}/{coord}/{dataset}'))
                if h5_file_idx == 0:
                    self.coordinateset[coord][dataset] = np.zeros((self.num_time_steps, self.num_files))
                self.coordinateset[coord][dataset][:, h5_file_idx] = data
    
    def process_frametransformsset(self, h5_filepath, h5_file_idx):
        """
        Processes the 'frametransformsset' group from an HDF5 file.
        
        WARNING: This method opens the file multiple times and is slow.
        The jam_analysis() method now uses optimized internal methods instead.

        Reads data for frame transformations (coordinates or transformation matrices)
        and stores it in the `self.frametransformsset` dictionary.
        Note: This method includes a print statement indicating it has not been thoroughly tested.

        Args:
            h5_filepath (str): Path to the HDF5 file.
            h5_file_idx (int): Index of the current file being processed.
        """
        ##### JAN.11.2022 - AAGATTI
        ##### HAVENT TESTED THE BELOW YET - THE EXAMPLE .h5 I USED DID NOT HAVE THIS DATATYPE
        print('PROCESSING FRAMETRANSFORMSET => THIS HAS NOT BEEN TESTED BEFORE, PLEASE VERIFY IF IT WORKS')
        frames = get_h5_output(h5_filepath, f'/{self.base_name}/{self.frametransformsset_name}')
        for frame_idx, frame in enumerate(frames):
            outcomes = get_h5_output(h5_filepath, f'/{self.base_name}/{self.frametransformsset_name}/{frame}')
            for outcome_idx, outcome in enumerate(outcomes):
                if 'coordinates' in outcome:
                    transform_type = 'coordinates'
                elif 'transformation_matrix' in outcome:
                    transform_type = 'transformation_matrix'

                params = get_h5_output(h5_filepath, f'/{self.base_name}/{self.frametransformsset_name}/{frame}/{outcome}')
                groups, datasets = get_h5_groups_datasets(
                    h5_filepath, 
                    f'/{self.base_name}/{self.frametransformsset_name}/{frame}/{outcome}/',
                    params
                )
                for dataset_idx, dataset in enumerate(datasets):
                    data = np.asarray(get_h5_output(h5_filepath, f'/{self.base_name}/{self.frametransformsset_name}/{frame}/{outcome}/dataset'))
                    if dataset not in self.frametransformsset[transform_type]:
                        self.frametransformsset[transform_type] = {
                            dataset: np.zeros((self.num_time_steps, self.num_files))
                        }
                    self.frametransformsset[transform_type][dataset][:, h5_file_idx] = data

    # =========================================================================
    # Main analysis method - OPTIMIZED
    # =========================================================================

    def jam_analysis(
        self, 
        h5_file_list,
        base_name=None,
        names=None
    ):
        """
        Performs the main analysis by reading and processing data from a list of HDF5 files.
        
        OPTIMIZED: This method now opens each H5 file only ONCE instead of thousands
        of times, providing ~50x speedup on NAS storage.

        Iterates through the provided HDF5 files, checks for their existence and format.
        For each file, it extracts time information (for the first file) and then processes
        ForceSet, CoordinateSet, FrameTransformsSet, and any COMAK-specific data groups.

        Args:
            h5_file_list (list or tuple): A list or tuple of paths to HDF5 files.
            base_name (str, optional): The base group name within the HDF5 file (e.g., 'model').
                If None, uses the class default `self.base_name`. Defaults to None.
            names (list, optional): A list of names to associate with each file. If None,
                files are named by their index. Defaults to None.

        Raises:
            Exception: If `h5_file_list` is not a list or tuple.
            Exception: If any file in `h5_file_list` is not in .h5 format.
        """
        if base_name is not None:
            self.base_name = base_name

        if type(h5_file_list) not in (list, tuple):
            raise Exception(f'`h5_file_list` is type: {type(h5_file_list)} and should be type `list` or `tuple`')
        else:
            self.h5_file_list = h5_file_list
        
        self.num_files = len(h5_file_list)

        if names is not None:
            self.names = names
        else:
            for idx in range(self.num_files):
                self.names.append(str(idx))
        
        # Read each h5 file
        for h5_file_idx, h5_filepath in enumerate(self.h5_file_list):
            # Test to make sure file exists
            if not os.path.exists(h5_filepath):
                print(f'File does not exist: {h5_filepath}')
                self.num_missing_files += 1
                self.missing_files.append(
                    {'idx': h5_file_idx,
                     'path': h5_filepath 
                    }
                )
                continue

            # Test to make sure that it is an .h5 file being passed 
            filename = os.path.basename(h5_filepath)

            if not filename.endswith('.h5'):
                raise Exception(f'File: {filename} is not `.h5` format!')

            # OPTIMIZED: Open file ONCE and process everything
            with h5py.File(h5_filepath, "r") as f:
                # Get time information from first file
                if h5_file_idx == 0:
                    self.time = np.array(f['/time'])
                    self.num_time_steps = len(self.time)
                
                # Get the data groups in the h5 file
                if f'/{self.base_name}' in f:
                    model_group = f[f'/{self.base_name}']
                    h5_groups = list(model_group.keys())
                    
                    for group in h5_groups:
                        if group == self.forceset_name:
                            self._process_forceset_fast(f, h5_file_idx)
                        elif group == self.coordset_name:
                            self._process_coordinateset_fast(f, h5_file_idx)
                        elif group == self.frametransformsset_name:
                            self._process_frametransformsset_fast(f, h5_file_idx)
                
                # Process COMAK data if it exists
                self._process_comak_fast(f, h5_file_idx)
    
    def plot_muscle_output(self, muscle_name, param_name, fontsize=20, linewidth=2, ax=None, label=None):
        """
        Plots a specific muscle output parameter over time for all loaded files.

        Args:
            muscle_name (str): The name of the muscle (e.g., 'gastroc_med').
            param_name (str): The name of the parameter to plot (e.g., 'activation', 'fiber_length').
            fontsize (int, optional): Fontsize for plot labels (not currently used for y-label). Defaults to 20.
            linewidth (int, optional): Linewidth for the plot. Defaults to 2.
            ax (matplotlib.axes.Axes, optional): An existing Matplotlib axes object to plot on.
                If None, a new plot is created. Defaults to None.
            label (str, optional): Label for the plotted line. Defaults to None.
        """
        for file_idx in range(self.num_files):
            if ax is None:
                plt.plot(
                    self.forceset['Muscle'][muscle_name][param_name][:,file_idx], 
                    linewidth=linewidth,
                    label=label
                )
            else:
                ax.plot(
                    self.forceset['Muscle'][muscle_name][param_name][:,file_idx], 
                    linewidth=linewidth,
                    label=label
                )
